# ------------------------------------------
# DB service for drupal
#
apiVersion: v1
kind: Service
metadata:
  name: mysqldb   ## the DATABASE_SERVER environment variable for Drupal
  labels:
    app: drupal
spec:
  ports:
    - port: 3306
  selector:
    app: drupal
    tier: mysql
  # headless service
  clusterIP: None
---
# ------------------------------------------
# Database deployment for Drupal
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: drupal
spec:
  selector:
    matchLabels:
      app: drupal
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: drupal
        tier: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name:  MYSQL_DATABASE
          value: drupal8
        - name:  MYSQL_USER
          value: drupal8
        - name:  MYSQL_PASSWORD   ## should be a secret, see below
          value: drupal8
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
